name: my-eff
version: 0.1.0.0
github: "githubuser/my-eff"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2018 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/my-eff#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - megaparsec
  - parser-combinators
  - hspec
  - QuickCheck
  - transformers
  - mtl

library:
  source-dirs: src

executables:
  my-eff-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -W
      - -with-rtsopts=-N
    dependencies:
      - my-eff

tests:
  my-eff-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - my-eff
